version: '3.7'

services:

  hub:
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=5

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
